import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import ThemeProvider from "@/lib/Providers/ThemeProvider";

const roboto = Roboto({
  variable: "--roboto",
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--poppins",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kv-tarif24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.className} antialiased`}>
        <AntdRegistry>
          <ThemeProvider>{children}</ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
